// <auto-generated />
using System;
using EloGreen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EloGreen.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EloGreen.Domain.Entities.CarbonTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("TX_ACTIVITY_DESC");

                    b.Property<decimal>("CarbonEmitted")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("NR_CARBON_EMITTED");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("TrackingDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_TRACKING");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("TB_EG_CARBON_TRACKING", (string)null);
                });

            modelBuilder.Entity("EloGreen.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("BaseCarbonFootprint")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("NR_CARBON_FOOTPRINT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TX_DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TX_NAME");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("TB_EG_PRODUCT", (string)null);
                });

            modelBuilder.Entity("EloGreen.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_DOCUMENT");

                    b.Property<int>("IsEsgCertified")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ST_ESG_CERTIFIED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("TX_NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IDX_SUP_NAME");

                    b.ToTable("TB_EG_SUPPLIER", (string)null);
                });

            modelBuilder.Entity("EloGreen.Domain.Entities.CarbonTracking", b =>
                {
                    b.HasOne("EloGreen.Domain.Entities.Product", "Product")
                        .WithMany("CarbonTrackings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TRACKING_PRODUCT");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EloGreen.Domain.Entities.Product", b =>
                {
                    b.HasOne("EloGreen.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCT_SUPPLIER");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("EloGreen.Domain.Entities.Product", b =>
                {
                    b.Navigation("CarbonTrackings");
                });

            modelBuilder.Entity("EloGreen.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
